"""add hostel_id to users

Revision ID: 1fc106889ad9
Revises: e7df7131024a
Create Date: 2026-09-25 16:08:28.672458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc106889ad9'
down_revision: Union[str, Sequence[str], None] = 'e7df7131024a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hostel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'hostels', ['hostel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'hostel_id')
    # ### end Alembic commands ###
