"""create technician skills table

Revision ID: e7df7131024a
Revises: ca5c58a857ea
Create Date: 2026-09-24 22:41:09.077432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7df7131024a'
down_revision: Union[str, Sequence[str], None] = 'ca5c58a857ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technician_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['complaint_categories.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technician_skills')
    # ### end Alembic commands ###
